/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LuckyProfiler_ */

#ifndef _Included_LuckyProfiler_
#define _Included_LuckyProfiler_
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LuckyProfiler_
 * Method:    computeAngs
 * Signature: ([I[I[SIII)V
 */
JNIEXPORT void JNICALL Java_LuckyProfiler_1_computeAngs
  (JNIEnv *, jobject, jintArray, jintArray, jshortArray, jint, jint, jint);

/*
 * Class:     LuckyProfiler_
 * Method:    getSkeleton
 * Signature: ([SII)[I
 */
JNIEXPORT jintArray JNICALL Java_LuckyProfiler_1_getSkeleton
  (JNIEnv *, jobject, jshortArray, jint, jint);

/*
 * Class:     LuckyProfiler_
 * Method:    getAngs
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_LuckyProfiler_1_getAngs
  (JNIEnv *, jobject);

/*
 * Class:     LuckyProfiler_
 * Method:    computeRCadiAndRelatedLocIndex
 * Signature: ([S[I[IIII)V
 */
JNIEXPORT void JNICALL Java_LuckyProfiler_1_computeRCadiAndRelatedLocIndex
  (JNIEnv *, jobject, jshortArray, jintArray, jintArray, jint, jint, jint);

/*
 * Class:     LuckyProfiler_
 * Method:    getRCadi
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_LuckyProfiler_1_getRCadi
  (JNIEnv *, jobject);

/*
 * Class:     LuckyProfiler_
 * Method:    getRelatedLocIndex
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_LuckyProfiler_1_getRelatedLocIndex
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
